#!/usr/bin/env bash
# Install (or remove) the three systemd *user* services.
#
# The unit files are generated here rather than committed, because they need the
# absolute path of wherever you cloned this repo.
#
#   ./install.sh            install and start
#   ./install.sh --uninstall stop, disable and delete the units

set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
# Resolved without `set -e` aborting first, so preflight can report it nicely.
PY="$(command -v python3 || true)"

SERVICES=(tablet-screen tablet-screen-layout tablet-screen-tunnel)

c_ok() { printf '\033[32m%s\033[0m\n' "$*"; }
c_err() { printf '\033[31m%s\033[0m\n' "$*" >&2; }

uninstall() {
	for s in "${SERVICES[@]}"; do
		systemctl --user disable --now "$s.service" >/dev/null 2>&1 || true
		rm -f "${UNIT_DIR}/${s}.service"
	done
	systemctl --user daemon-reload
	c_ok "Removed: ${SERVICES[*]}"
	echo "Your .env and the scripts are untouched."
}

preflight() {
	local missing=0
	if [ -z "$PY" ]; then
		c_err "missing: python3"
		missing=1
	fi
	for cmd in adb gst-inspect-1.0; do
		command -v "$cmd" >/dev/null 2>&1 || {
			c_err "missing: $cmd"
			missing=1
		}
	done
	if [ -n "$PY" ]; then
		"$PY" -c 'import gi, dbus; gi.require_version("Gst","1.0")' 2>/dev/null || {
			c_err "missing python3 gi/Gst/dbus bindings"
			missing=1
		}
	fi
	if command -v gst-inspect-1.0 >/dev/null 2>&1; then
		gst-inspect-1.0 --exists pipewiresrc || {
			c_err "missing GStreamer element: pipewiresrc"
			missing=1
		}
		gst-inspect-1.0 --exists jpegenc || {
			c_err "missing GStreamer element: jpegenc"
			missing=1
		}
	fi
	if [ "$missing" -ne 0 ]; then
		echo
		echo "On Ubuntu/Debian:"
		echo "  sudo apt install adb python3-gi python3-dbus \\"
		echo "    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \\"
		echo "    gstreamer1.0-pipewire gstreamer1.0-vaapi"
		exit 1
	fi

	# The whole design rests on Mutter's virtual-monitor API.
	if ! gdbus introspect --session --dest org.gnome.Mutter.ScreenCast \
		--object-path /org/gnome/Mutter/ScreenCast >/dev/null 2>&1; then
		c_err "org.gnome.Mutter.ScreenCast is unavailable."
		c_err "This needs a running GNOME session on Wayland."
		exit 1
	fi
	c_ok "Dependencies OK"
}

write_unit() {
	local name="$1" desc="$2" exec="$3" extra="${4:-}"
	cat >"${UNIT_DIR}/${name}.service" <<EOF
# Generated by install.sh - re-run it after moving the repo.
[Unit]
Description=${desc}
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
WorkingDirectory=${REPO_DIR}
ExecStart=${exec}
Restart=always
RestartSec=5
${extra}

[Install]
WantedBy=default.target
EOF
}

install() {
	preflight
	mkdir -p "$UNIT_DIR"

	if [ ! -f "${REPO_DIR}/.env" ]; then
		cp "${REPO_DIR}/.env.example" "${REPO_DIR}/.env"
		c_ok "Created .env from .env.example"
	fi
	chmod +x "${REPO_DIR}/usb-tunnel.sh" "${REPO_DIR}/mjpeg-screen.py" \
		"${REPO_DIR}/auto-layout.py" "${REPO_DIR}/bench.sh" 2>/dev/null || true

	write_unit tablet-screen \
		"Tablet second screen (MJPEG, display-only, on demand)" \
		"${PY} ${REPO_DIR}/mjpeg-screen.py"
	write_unit tablet-screen-layout \
		"Pin the tablet's virtual monitor in the GNOME display layout" \
		"${PY} ${REPO_DIR}/auto-layout.py"
	# KillMode=mixed so systemd does not reap adb's background server.
	write_unit tablet-screen-tunnel \
		"USB reverse tunnel + keep-awake for the tablet screen" \
		"${REPO_DIR}/usb-tunnel.sh" \
		"KillMode=mixed"

	systemctl --user daemon-reload
	systemctl --user enable --now "${SERVICES[@]/%/.service}"
	sleep 2
	echo
	for s in "${SERVICES[@]}"; do
		printf '  %-28s %s\n' "$s" "$(systemctl --user is-active "$s.service")"
	done
	echo
	c_ok "Installed. Edit .env, then:"
	echo "  systemctl --user restart ${SERVICES[*]}"
	echo
	echo "On the tablet, open:  http://127.0.0.1:$(
		grep -E '^HTTP_PORT=' "${REPO_DIR}/.env" 2>/dev/null | cut -d= -f2 || echo 8099
	)"
}

case "${1:-install}" in
--uninstall | uninstall) uninstall ;;
install) install ;;
*)
	echo "usage: $0 [--uninstall]" >&2
	exit 1
	;;
esac
